const STORAGE_KEY='campusFindItemsV1';const CLAIM_KEY='campusFindClaimsV1';
const seedItems=[
{id:'i1',type:'lost',name:'Black wireless earbuds',category:'Electronics',location:'Central Library',date:'2026-09-08',description:'Small black charging case. Last seen on a table near the second-floor windows.',status:'open',mine:false},
{id:'i2',type:'found',name:'Student ID card',category:'ID Cards',location:'Cafeteria',date:'2026-09-09',description:'A student ID card was handed to the cafeteria counter. Private details are hidden.',status:'open',mine:true},
{id:'i3',type:'found',name:'Blue water bottle',category:'Other',location:'Basketball Court',date:'2026-09-07',description:'Blue insulated bottle with a small sticker near the lid.',status:'open',mine:false},
{id:'i4',type:'lost',name:'Data Structures notebook',category:'Books',location:'CS Block, Room 204',date:'2026-09-06',description:'A ruled notebook with handwritten class notes and a green cover.',status:'open',mine:true},
{id:'i5',type:'found',name:'Silver key ring',category:'Keys',location:'Main Auditorium',date:'2026-09-05',description:'Two keys on a plain silver ring, found under a rear seat.',status:'returned',mine:false},
{id:'i6',type:'lost',name:'Grey laptop sleeve',category:'Bags',location:'Innovation Lab',date:'2026-09-04',description:'Grey fabric 14-inch sleeve with a front zipper pocket.',status:'open',mine:false}
];
let items=load(STORAGE_KEY,seedItems);let claims=load(CLAIM_KEY,[]);let activeItemId=null;
const icons={'Electronics':'E','ID Cards':'ID','Keys':'K','Books':'B','Bags':'BG','Wallets':'W','Other':'?'};
function load(key,fallback){try{const value=JSON.parse(localStorage.getItem(key));return Array.isArray(value)?value:fallback}catch{return fallback}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(items));localStorage.setItem(CLAIM_KEY,JSON.stringify(claims))}
function escapeHtml(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function friendlyDate(date){return new Date(date+'T00:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'})}
function card(item){return `<article class="item-card" tabindex="0" role="button" data-id="${item.id}" aria-label="View ${escapeHtml(item.name)}"><div class="card-top"><div class="item-icon" aria-hidden="true">${icons[item.category]||'◇'}</div><span class="badge ${item.status==='returned'?'returned':item.type}">${item.status==='returned'?'Returned':item.type}</span></div><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.description)}</p><div class="card-meta"><span>${escapeHtml(item.category)}</span><span>${escapeHtml(item.location)}</span><span>${friendlyDate(item.date)}</span></div></article>`}
function renderItems(){const q=document.querySelector('#searchInput').value.trim().toLowerCase();const type=document.querySelector('#typeFilter').value;const category=document.querySelector('#categoryFilter').value;const filtered=items.filter(i=>(type==='all'||i.type===type)&&(category==='all'||i.category===category)&&`${i.name} ${i.description} ${i.location}`.toLowerCase().includes(q));document.querySelector('#itemGrid').innerHTML=filtered.map(card).join('');document.querySelector('#emptyState').hidden=filtered.length>0;document.querySelector('#openCount').textContent=items.filter(i=>i.status==='open').length;document.querySelector('#returnedCount').textContent=items.filter(i=>i.status==='returned').length;document.querySelector('#matchCount').textContent=potentialMatches();document.querySelectorAll('.item-card').forEach(el=>{el.onclick=()=>showDetail(el.dataset.id);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();showDetail(el.dataset.id)}}})}
function potentialMatches(){let count=0;items.filter(i=>i.type==='lost'&&i.status==='open').forEach(l=>items.filter(i=>i.type==='found'&&i.status==='open').forEach(f=>{if(l.category===f.category&&(l.location===f.location||Math.abs(new Date(l.date)-new Date(f.date))<259200000))count++}));return count}
function showDetail(id){const i=items.find(x=>x.id===id);if(!i)return;activeItemId=id;const action=i.status==='returned'?'<button class="button secondary close-detail">Close</button>':i.mine?`<button class="button secondary" data-return="${i.id}">Mark as returned</button>`:`<button class="button primary" data-claim="${i.id}">This may be mine</button>`;document.querySelector('#detailContent').innerHTML=`<div class="detail-title"><div><span class="eyebrow">${i.type} item report</span><h2>${escapeHtml(i.name)}</h2></div><button class="icon-button close-detail" aria-label="Close">×</button></div><div class="detail-description">${escapeHtml(i.description)}</div><div class="detail-facts"><div class="fact"><span>Category</span><strong>${escapeHtml(i.category)}</strong></div><div class="fact"><span>Date</span><strong>${friendlyDate(i.date)}</strong></div><div class="fact"><span>Location</span><strong>${escapeHtml(i.location)}</strong></div><div class="fact"><span>Status</span><strong>${i.status==='returned'?'Returned to owner':'Open'}</strong></div></div><div class="modal-actions">${action}</div>`;document.querySelector('#detailDialog').showModal();document.querySelectorAll('.close-detail').forEach(b=>b.onclick=()=>document.querySelector('#detailDialog').close());document.querySelector('[data-claim]')?.addEventListener('click',e=>openClaim(e.currentTarget.dataset.claim));document.querySelector('[data-return]')?.addEventListener('click',e=>markReturned(e.currentTarget.dataset.return))}
function openReport(type){const d=document.querySelector('#reportDialog');document.querySelector('#reportForm').reset();document.querySelector('#reportType').value=type;document.querySelector('#reportEyebrow').textContent=type==='lost'?'Missing item':'Recovered item';document.querySelector('#reportTitle').textContent=type==='lost'?'Report a lost item':'Report a found item';document.querySelector('[name=eventDate]').value=new Date().toISOString().slice(0,10);d.showModal()}
function openClaim(id){document.querySelector('#detailDialog').close();document.querySelector('#claimForm').reset();document.querySelector('#claimItemId').value=id;document.querySelector('#claimDialog').showModal()}
function markReturned(id){const item=items.find(i=>i.id===id);if(item){item.status='returned';save();renderAll();document.querySelector('#detailDialog').close();toast('Item marked as returned.')}}
function renderMyReports(){const mine=items.filter(i=>i.mine);document.querySelector('#myReportsList').innerHTML=mine.length?mine.map(i=>`<div class="list-row"><div class="item-icon">${icons[i.category]||'◇'}</div><div><h3>${escapeHtml(i.name)}</h3><p>${i.type.toUpperCase()} · ${escapeHtml(i.location)} · ${friendlyDate(i.date)}</p></div><div class="row-actions"><span class="badge ${i.status==='returned'?'returned':i.type}">${i.status}</span><button class="small-button" data-view-item="${i.id}">View</button></div></div>`).join(''):'<div class="blank-panel">You have not created any reports yet.</div>';document.querySelectorAll('[data-view-item]').forEach(b=>b.onclick=()=>showDetail(b.dataset.viewItem))}
function renderClaims(){const received=claims.filter(c=>items.find(i=>i.id===c.itemId)?.mine);document.querySelector('#claimsList').innerHTML=received.length?received.map(c=>{const i=items.find(x=>x.id===c.itemId);return `<div class="list-row"><div class="item-icon">CL</div><div><h3>Claim for ${escapeHtml(i?.name||'item')}</h3><p>${escapeHtml(c.proof)} · ${friendlyDate(c.date)}</p></div><div class="row-actions"><span class="badge ${c.status==='approved'?'returned':'lost'}">${c.status}</span>${c.status==='pending'?`<button class="small-button" data-approve="${c.id}">Approve</button>`:''}</div></div>`}).join(''):'<div class="blank-panel">No claims need your review.</div>';document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>approveClaim(b.dataset.approve))}
function approveClaim(id){const c=claims.find(x=>x.id===id);if(!c)return;c.status='approved';const item=items.find(i=>i.id===c.itemId);if(item)item.status='returned';save();renderAll();toast('Claim approved and item marked returned.')}
function renderAll(){renderItems();renderMyReports();renderClaims()}
function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
document.querySelectorAll('[data-open-report]').forEach(b=>b.onclick=()=>openReport(b.dataset.openReport));document.querySelectorAll('.close-modal').forEach(b=>b.onclick=()=>document.querySelector('#reportDialog').close());document.querySelectorAll('.close-claim').forEach(b=>b.onclick=()=>document.querySelector('#claimDialog').close());
document.querySelector('#reportForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);items.unshift({id:'i'+Date.now(),type:f.get('reportType'),name:f.get('itemName').trim(),category:f.get('category'),location:f.get('location').trim(),date:f.get('eventDate'),description:f.get('description').trim(),status:'open',mine:true});save();renderAll();document.querySelector('#reportDialog').close();toast('Your report is now live.')};
document.querySelector('#claimForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);claims.unshift({id:'c'+Date.now(),itemId:f.get('itemId'),proof:f.get('proof').trim(),status:'pending',date:new Date().toISOString().slice(0,10)});save();renderAll();document.querySelector('#claimDialog').close();toast('Claim sent privately to the finder.')};
['searchInput','typeFilter','categoryFilter'].forEach(id=>document.querySelector('#'+id).addEventListener(id==='searchInput'?'input':'change',renderItems));
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));document.querySelectorAll('.nav-link').forEach(n=>n.classList.remove('active'));document.querySelector('#'+(b.dataset.view==='home'?'homeView':b.dataset.view==='my-reports'?'myReportsView':'claimsView')).classList.add('active-view');b.classList.add('active');window.scrollTo({top:0})});
document.querySelector('#resetDemo').onclick=()=>{items=structuredClone(seedItems);claims=[];save();renderAll();toast('Demo data restored.')};
renderAll();
